"""""""""""""""""""""""""""""""""""""
"                                   "
" This is my personal configuration "
" Daniel Córdova A.                 "
"                                   "
"""""""""""""""""""""""""""""""""""""

" Basic confs
if has('gui_running')
    colorscheme desertEx
    set lines=999 columns=999
else
    colorscheme wombat256i
endif

set encoding=utf-8
set number
set expandtab
set tabstop=4
set cindent
set shiftwidth=4
set mouse=a
set ruler
set showcmd
set title
set nocp
set noshowmode
set hlsearch
syntax on
set guifont=Inconsolata\ for\ Powerline\ Nerd\ Font\ Complete\ 12
" Vim tell Leave INSERT mode
au InsertLeave * set nopaste

"""""""""""
" Sources "
"""""""""""

" Custom Functions
source ~/.vim/confs/custom-functions.vim
" Nerd Stuff
source ~/.vim/confs/nerd-stuff.vim
" Various Confs
source ~/.vim/confs/various.vim
" Lightline
source ~/.vim/confs/lightline.vim
" Pastemode automatically
source ~/.vim/confs/pastemode.vim

" Complete syntax
set omnifunc=syntaxcomplete#Complete
set completeopt+=longest,menuone

"""""""""""""""""""""
" Mapping Shortcuts "
"""""""""""""""""""""

" Lazy mappings
map 1 :NERDTreeToggle<cr>
map 2 :TagbarToggle<cr>
" Toggle wrapping long text
map 3 :call ToggleWrap()<CR>

" Visual Block
nnoremap vb <C-v>

" Tabs
" Create new Tab
map za :tabnew<cr>
" Move to the right tab
map zx gt
" Move to the left tab
map zz gT

" Simple Behavior
" Paste text from clipboard with 'Ctrl+v'
map <C-v> "+gP
" Select all text with 'Ctrl+a'
map <C-a> ggVG

" NERDTree
" Move between panes
map <C-Left> <C-w>h
map <C-Right> <C-w>l

" NERDCommenter
" Toggle Comment line or selected text with 'Ctrl+/'
nmap <C-_> <leader>c<Space>
vmap <C-_> <leader>c<Space>

" Omnicompletion
imap <expr> <C-Space> pumvisible() \|\| &omnifunc == '' ?
            \ "\<lt>C-n>" :
            \ "\<lt>C-x>\<lt>C-o><c-r>=pumvisible() ?" .
            \ "\"\\<lt>c-n>\\<lt>c-p>\\<lt>c-n>\" :" .
            \ "\" \\<lt>bs>\\<lt>C-n>\"\<CR>"
imap <C-@> <C-Space>
imap <C-k> <c-r>=SmartOmniComplete()<CR>

" Vundle plugin manager
set rtp+=~/.vim/bundle/Vundle.vim
set nocompatible
filetype off
call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'scrooloose/nerdtree'
    Plugin 'scrooloose/nerdcommenter'
    Plugin 'Xuyuanp/nerdtree-git-plugin'
    Plugin 'majutsushi/tagbar'
    Plugin 'itchyny/lightline.vim'
    Plugin 'ryanoasis/vim-devicons'
    Plugin 'alvan/vim-closetag'
    Plugin 'calebsmith/vim-lambdify'
    Plugin 'smancill/conky-syntax.vim'
    Plugin 'pangloss/vim-javascript'
    Plugin 'udalov/kotlin-vim'
call vundle#end()
filetype plugin indent on

