[general]
import       = ["~/.config/alacritty/catppuccin-frappe.toml"]

[window]
opacity      = 0.95
dimensions = { columns = 320, lines = 15 }
position = { x = 0, y = 785 }
decorations = "None"

[font]
normal       = { family = "Inconsolata Nerd Font Mono", style = "Medium" }
bold         = { family = "Inconsolata Nerd Font Mono", style = "Bold" }
italic       = { family = "Inconsolata Nerd Font Mono", style = "Italic" }
bold_italic  = { family = "Inconsolata Nerd Font Mono", style = "Bold Italic" }
size         = 12.0

