#!/bin/sh

# Launch script that switch to external monitor
# or laptop monitor when cable is connected/disconnected
exec ~/.config/custom_scripts/external_monitor.sh &

# Launch Keyboard config layout
# numpad:mac -> allow to use numeric keypad without press numblock key
setxkbmap -layout us -variant altgr-intl -option deadkeys -option numpad:mac &

# Turn off bell sounds
xset b off &

# Set wallpaper
(sleep 0.5s && feh --bg-center ~/Pictures/futuristic/futuristic4.jpg) &

# Launch Tint2 bar
(sleep 0.5s && tint2) &

# Set custom composition
(sleep 0.5s && picom --config ~/.config/picom.conf) &

# Launch Conky System Monitor with custom config
(sleep 0.5s && conky -c ~/.config/conkyrc) &

# Launch notification system
(sleep 0.5s && dunst) &

# Load Xresources
(sleep 0.2s && xrdb ~/.Xresources) &

# Volume Systray
(sleep 0.2s && pasystray) &

# Launch Network-Manager app
(sleep 0.5s && nm-applet --indicator) &

# Start Light Locker
(sleep 0.5s && light-locker) &

# Disable TouchScreen (Only Asus has TouchScreen)
(sleep 0.5s &&xinput disable "ELAN Touchscreen") &

# Davmail Gateway
(sleep 0.5s && /opt/davmail/davmail) &

