#!/bin/sh

# Launch script that switch to external monitor
# or laptop monitor when cable is connected/disconnected
exec ~/.config/custom_scripts/external_monitor.sh &

# Launch Keyboard config layout
# numpad:mac -> allow to use numeric keypad without press numblock key
setxkbmap -layout us -variant altgr-intl -option deadkeys -option numpad:mac &

# Set wallpaper
(sleep 0.5s && feh --bg-center ~/Pictures/futuristic/futuristic4.jpg) &

# Launch Tint2 bar
(sleep 0.5s && tint2) &

# Set custom composition
(sleep 0.5s && picom --config ~/.config/picom.conf) &
#(sleep 0.5s && xcompmgr -l -5 -t -5 -r 4 -cC -o.55) &

# Launch Conky System Monitor with custom config
(sleep 0.5s && conky -c ~/.config/conkyrc) &

# Launch notification system
(sleep 0.5s && dunst) &

# Load Xresources
(xrdb ~/.Xresources) &

# Launch Network-Manager app
(sleep 0.5s && nm-applet --indicator) &

# Turn off bell sounds
xset b off &

# Start Light Locker
light-locker &

# Disable TouchScreen (Only Asus has TouchScreen)
xinput disable "ELAN Touchscreen" &

# Davmail Gateway
(sleep 0.5s && /opt/davmail/davmail) &
